// produk/productsData.ts
export const productsData = [
  {
    id: '1',
    name: 'IPHONE',
    price: 50000,
    category: 'HP',
    img: require('../../assets/images/iphone.jpg'),
    models: ['iPhone 11', 'iPhone 12', 'iPhone 13'],
    ram: ['4GB', '6GB', '8GB'],
  },
  {
    id: '2',
    name: 'REDMI',
    price: 40000,
    category: 'HP',
    img: require('../../assets/images/redmi.jpg'),
    models: ['Note 9', 'Note 10', 'Note 11'],
    ram: ['4GB', '6GB'],
  },
  {
    id: '3',
    name: 'OPPO',
    price: 45000,
    category: 'HP',
    img: require('../../assets/images/oppo.jpg'),
    models: ['A53', 'A54', 'A55'],
    ram: ['4GB', '6GB'],
  },
  {
    id: '4',
    name: 'SAMSUNG',
    price: 55000,
    category: 'HP',
    img: require('../../assets/images/samsung.jpg'),
    models: ['S20', 'S21', 'S22'],
    ram: ['6GB', '8GB'],
  },
  {
    id: '5',
    name: 'LENOVO',
    price: 100000,
    category: 'Laptop',
    img: require('../../assets/images/laptop.jpg'),
    models: ['IdeaPad', 'Legion'],
    ram: ['8GB', '16GB'],
  },
  {
    id: '6',
    name: 'DELL',
    price: 120000,
    category: 'Laptop',
    img: require('../../assets/images/laptop2.jpg'),
    models: ['Inspiron', 'XPS'],
    ram: ['8GB', '16GB'],
  },
  {
    id: '7',
    name: 'CANON',
    price: 75000,
    category: 'Camera',
    img: require('../../assets/images/canon.jpg'),
    models: ['EOS 200D', 'EOS 250D'],
    ram: [''],
  },
  {
    id: '8',
    name: 'NIKON',
    price: 80000,
    category: 'Camera',
    img: require('../../assets/images/nikon.jpg'),
    models: ['D3500', 'D5600'],
    ram: [''],
  },
];
